# Generated by Django 4.2.23 on 2025-08-14 13:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bookable item', max_length=200)),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Number of people or reservations this item can accommodate at one time', validators=[django.core.validators.MinValueValidator(1)])),
                ('info', models.TextField(blank=True, help_text='Additional descriptive information (e.g., location, special features)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is available for booking')),
            ],
            options={
                'verbose_name': 'Bookable Item',
                'verbose_name_plural': 'Bookable Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookingTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(help_text='Start time of the booking slot')),
                ('time_length', models.DurationField(help_text='Length of the time slot (e.g., 30 minutes, 1 hour)')),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('booked', 'Booked')], default='available', help_text='Current booking status of the time slot', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookable_item', models.ForeignKey(help_text='The bookable item this time slot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='bookings.bookableitem')),
            ],
            options={
                'verbose_name': 'Booking Time Slot',
                'verbose_name_plural': 'Booking Time Slots',
                'ordering': ['time_start'],
                'unique_together': {('bookable_item', 'time_start')},
            },
        ),
    ]
